apiVersion: apps/v1
kind: Deployment
metadata:
  name: peoples-coin-backend
  labels:
    app: peoples-coin-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peoples-coin-backend
  template:
    metadata:
      labels:
        app: peoples-coin-backend
    spec:
      containers:
      - name: peoples-coin-backend
        image: gcr.io/heroic-tide-428421-q7/peoples-coin-backend:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB_URI
          valueFrom:
            secretKeyRef:
              name: peoples-coin-secrets
              key: POSTGRES_DB_URI
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: peoples-coin-secrets
              key: REDIS_URL
        - name: RABBITMQ_URL
          value: amqp://guest:guest@35.199.15.190:5672/
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: peoples-coin-backend-service
spec:
  selector:
    app: peoples-coin-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

